name: ykcnblogs
version: 1
accesskey: kymzmlom44
cron:
    - description: cron get cnblogs
      url: /record_cn_blogs.php
      schedule: */5 * * * *
    - description: cron get cnblogs_php
      url: /record_cn_php_blogs.php
      schedule: */5 * * * *